name: Continuous Integration Orchestrator

on:
  push:
  pull_request: 
    branches: [ main, master ]
  workflow_dispatch:

jobs: 
  # Job 1 : Test for the game Two Ships
  test-two-ships:
    name: Test Two Ships
    uses: ./github/worflows/reusable-game-check.yml
    with:
      games-path: games/two-shops-passing-in-the-night
  
  # Job 2 : Test for the game space word
  test-space-word:
    name: Test Space word
    uses: ./.github/worflows/reusable-game-check.yml
    with:
      game-path: games/spaceword